"""Weight Gurus integration constants"""
DOMAIN = "weight_gurus"

ATTR_ACCESS_TOKEN = "accessToken"
ATTR_ACCOUNT = "account"
ATTR_DECIMAL_VALUES = "decimalValues"
ATTR_DEFAULT_NAME = "Weight Gurus"
ATTR_EMAIL_REGEX = "(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)"
ATTR_ENTRY_TIMESTAMP = "entryTimestamp"
ATTR_FIRST_NAME = "firstName"
ATTR_ICON = "mdi:scale-bathroom"
ATTR_LAST_NAME = "lastName"
ATTR_OPERATIONS = "operations"
ATTR_URL = "https://api.weightgurus.com/v3"
ATTR_WEIGHT = "weight"
